<?php
/**
 * Class UploadInput.php , Last changed 11.06.2017
 * This file is part of the fpvspots
 * Copyright (c) 2017 Lukáš Vlček (http://www.vlceklukas.cz)
 */

namespace App\Models\Form;

use Nette;

class UploadInput extends Nette\Forms\Controls\UploadControl
{
    public function __construct($label = NULL, $multiple = FALSE)
    {
        parent::__construct($label, $multiple);
    }

    public function getControl()
    {
        $control = parent::getControl(); // TODO: Change the autogenerated stub

        $container = Nette\Utils\Html::el('div')
            ->setAttribute('class','fancy-file-upload');

        $control->setAttribute('class', 'custom-file-upload custom-file-upload-hidden');

        $control->setAttribute('data-btn-text', $this->getTranslator()->translate('default.buttons.selectFile'));

        $container->addHtml($control);

        return $container;
    }
}