<?php
/**
 * Class BaseComponent.php , Last changed 30.05.2017
 * This file is part of the fpvspots
 * Copyright (c) 2017 Lukáš Vlček (http://www.vlceklukas.cz)
 */

namespace App\AdminModule\Components;

use App\Presenters\BasePresenter;
use Nette;

class BaseComponent extends Nette\Application\UI\Control
{
	/**
	 * @param bool $throw
	 * @return Nette\Application\UI\Presenter|BasePresenter|NULL
	 */
	public function getPresenter($throw = TRUE)
	{
		return parent::getPresenter($throw); // TODO: Change the autogenerated stub
	}
}